sudo: false

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - INSTALL_WHEEL=0
  - INSTALL_WHEEL=1

matrix:
  fast_finish: true
  allow_failures:
  # 3.3 EOL Sept 2017
  - python: "3.3"
  # assume dev is unstable (even though it's released...Travis is slow)
  - python: "3.7-dev"

before_install:
  - pip install --requirement requirements-dev.txt
  - invoke build

install:
  - invoke install

before_script:
  - invoke clean
  - rm -rf claptrap* setup.py # eliminate any way to import the source

script:
  - invoke test --coverage

after_success:
  - codecov
