sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  fast_finish: true
  allow_failures:
  - python: "2.7"
  - python: "3.3"
  # assume dev is unstable (even though it's released...Travis is slow)
  - python: "3.7-dev"

install:
  - pip install -r requirements-dev.txt

script:
  - make test
  - make build

after_success:
  - codecov
